### ISSUE TITLE
can't convert Pathname into String (TypeError)

### ISSUE THREAD

**Issue by jasonkarns** [bblimke/webmock#1063]
Reopen of #127 

`stub_request(:post, Pathname("http://foo.test/path")).with(body:, headers:)`

<details>
<summary>backtrace</summary>

```
      TypeError:
        Can't convert Pathname into String.
      # /opt/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/addressable-2.8.7/lib/addressable/uri.rb:206:in `heuristic_parse'
      # /opt/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/webmock-3.23.1/lib/webmock/util/uri.rb:13:in `block in <class:URI>'
      # /opt/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/webmock-3.23.1/lib/webmock/util/uri.rb:29:in `heuristic_parse'
      # /opt/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/webmock-3.23.1/lib/webmock/util/uri.rb:17:in `block in <class:URI>'
      # /opt/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/webmock-3.23.1/lib/webmock/util/uri.rb:35:in `normalize_uri'
      # /opt/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/webmock-3.23.1/lib/webmock/request_pattern.rb:120:in `initialize'
      # /opt/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/webmock-3.23.1/lib/webmock/request_pattern.rb:88:in `new'
      # /opt/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/webmock-3.23.1/lib/webmock/request_pattern.rb:88:in `create_uri_pattern'
      # /opt/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/webmock-3.23.1/lib/webmock/request_pattern.rb:21:in `initialize'
      # /opt/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/webmock-3.23.1/lib/webmock/request_stub.rb:9:in `new'
      # /opt/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/webmock-3.23.1/lib/webmock/request_stub.rb:9:in `initialize'
      # /opt/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/webmock-3.23.1/lib/webmock/api.rb:9:in `new'
      # /opt/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/webmock-3.23.1/lib/webmock/api.rb:9:in `stub_request'
      # ./spec/chime/risk_vendors/risk_vendor_event/risk_vendor_event_resource_spec.rb:24:in `block (2 levels) in <top (required)>'
```
</details>

- on ruby 3.1.2
- webmock (3.23.1)
- addressable (2.8.7)

**Comment by bblimke** [comment]
Though it's a good idea to raise an Argument error.

**Comment by jasonkarns** [comment]
If it's intentional, that's fine. I just saw the old error and the conversation implied it was an acceptable input. (I prefer richer domain objects instead of primitive obsession codesmell, so it was a weird error that webmock wouldn't accept pathname.)

I'd probably rather not overtly raise exceptions, since webmock shouldn't _really_ care about the type. Only that it be something acceptable to Addressable. If webmock duplicates addressable's type checking, then it wouldn't be robust to future Addressable changes.
