### ISSUE TITLE
Excon is not being mocked

### ISSUE THREAD

**Issue by moxley** [bblimke/webmock#475]
Hi. WebMock doesn't seem to be hooking into `excon` for me. In the example below, I run `Net::HTTP.get('www.example.com', '/')`, which WebMock successfully intercepts. Then I run `Excon.get('http://www.example.com/')`, and WebMock lets it call out to the web and fetch the HTML document.

**Versions**

ruby (2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux])
webmock (1.9.3)
excon (0.45.3)

**Steps to Reproduce**

```
irb(main):001:0> require 'webmock'
=> true
irb(main):002:0> WebMock.disable_net_connect!
=> nil
irb(main):003:0> Net::HTTP.get('www.example.com', '/')
WebMock::NetConnectNotAllowedError: Real HTTP connections are disabled. Unregistered request: GET http://www.example.com/ with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'User-Agent'=>'Ruby'}

You can stub this request with the following snippet:

stub_request(:get, "http://www.example.com/").
  with(:headers => {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'User-Agent'=>'Ruby'}).
  to_return(:status => 200, :body => "", :headers => {})

============================================================
	from /home/hhadmin/.gem/ruby/2.1.2/gems/webmock-1.9.3/lib/webmock/http_lib_adapters/net_http.rb:107:in `request'
	from /opt/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:1280:in `request_get'
	from /opt/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:474:in `block in get_response'
	from /home/hhadmin/.gem/ruby/2.1.2/gems/webmock-1.9.3/lib/webmock/http_lib_adapters/net_http.rb:116:in `start_without_connect'
	from /home/hhadmin/.gem/ruby/2.1.2/gems/webmock-1.9.3/lib/webmock/http_lib_adapters/net_http.rb:131:in `start'
	from /opt/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:473:in `get_response'
	from /opt/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:455:in `get'
	from (irb):3
	from /opt/rubies/ruby-2.1.2/bin/irb:11:in `<main>'
irb(main):004:0> Excon.get('http://www.example.com/')
=> #<Excon::Response:0x007fb5acc0f788 @data={:body=>"<!doctype html>\n<html>\n<head>\n    <title>Example Domain</title>\n\n    <meta charset=\"utf-8\" />\n    <meta http-equiv=\"Content-type\" content=\"text/html; charset=utf-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n    <style type=\"text/css\">\n    body {\n        background-color: #f0f0f2;\n        margin: 0;\n        padding: 0;\n        font-family: \"Open Sans\", \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n        \n    }\n    div {\n        width: 600px;\n        margin: 5em auto;\n        padding: 50px;\n        background-color: #fff;\n        border-radius: 1em;\n    }\n    a:link, a:visited {\n        color: #38488f;\n        text-decoration: none;\n    }\n    @media (max-width: 700px) {\n        body {\n            background-color: #fff;\n        }\n        div {\n            width: auto;\n            margin: 0 auto;\n            border-radius: 0;\n            padding: 1em;\n        }\n    }\n    </style>    \n</head>\n\n<body>\n<div>\n    <h1>Example Domain</h1>\n    <p>This domain is established to be used for illustrative examples in documents. You may use this\n    domain in examples without prior coordination or asking for permission.</p>\n    <p><a href=\"http://www.iana.org/domains/example\">More information...</a></p>\n</div>\n</body>\n</html>\n", :headers=>{"Accept-Ranges"=>"bytes", "Cache-Control"=>"max-age=604800", "Content-Type"=>"text/html", "Date"=>"Wed, 06 May 2015 04:16:30 GMT", "Etag"=>"\"359670651\"", "Expires"=>"Wed, 13 May 2015 04:16:30 GMT", "Last-Modified"=>"Fri, 09 Aug 2013 23:54:35 GMT", "Server"=>"ECS (pae/3796)", "X-Cache"=>"HIT", "x-ec-custom-error"=>"1", "Content-Length"=>"1270"}, :status=>200, :status_line=>"HTTP/1.1 200 OK\r\n", :reason_phrase=>"OK", :remote_ip=>"93.184.216.34", :local_port=>35200, :local_address=>"10.0.2.15"}, @body="<!doctype html>\n<html>\n<head>\n    <title>Example Domain</title>\n\n    <meta charset=\"utf-8\" />\n    <meta http-equiv=\"Content-type\" content=\"text/html; charset=utf-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n    <style type=\"text/css\">\n    body {\n        background-color: #f0f0f2;\n        margin: 0;\n        padding: 0;\n        font-family: \"Open Sans\", \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n        \n    }\n    div {\n        width: 600px;\n        margin: 5em auto;\n        padding: 50px;\n        background-color: #fff;\n        border-radius: 1em;\n    }\n    a:link, a:visited {\n        color: #38488f;\n        text-decoration: none;\n    }\n    @media (max-width: 700px) {\n        body {\n            background-color: #fff;\n        }\n        div {\n            width: auto;\n            margin: 0 auto;\n            border-radius: 0;\n            padding: 1em;\n        }\n    }\n    </style>    \n</head>\n\n<body>\n<div>\n    <h1>Example Domain</h1>\n    <p>This domain is established to be used for illustrative examples in documents. You may use this\n    domain in examples without prior coordination or asking for permission.</p>\n    <p><a href=\"http://www.iana.org/domains/example\">More information...</a></p>\n</div>\n</body>\n</html>\n", @headers={"Accept-Ranges"=>"bytes", "Cache-Control"=>"max-age=604800", "Content-Type"=>"text/html", "Date"=>"Wed, 06 May 2015 04:16:30 GMT", "Etag"=>"\"359670651\"", "Expires"=>"Wed, 13 May 2015 04:16:30 GMT", "Last-Modified"=>"Fri, 09 Aug 2013 23:54:35 GMT", "Server"=>"ECS (pae/3796)", "X-Cache"=>"HIT", "x-ec-custom-error"=>"1", "Content-Length"=>"1270"}, @status=200, @remote_ip="93.184.216.34", @local_port=35200, @local_address="10.0.2.15">
```

**Comment by moxley** [comment]
Never mind, this is due to my old version of webmock. Having started a new project, I mistakenly thought I had a recent version.
