### ISSUE TITLE
Request_pattern#matches? fails on nil body and body :hash_including match

### ISSUE THREAD

**Issue by bombazook** [bblimke/webmock#502]
Is it a bug or a feature to fail request_pattern#matches? on nil body?
```
# /Users/admin/.rvm/gems/ruby-2.1.1@mygem/gems/webmock-1.21.0/lib/webmock/util/json.rb:24:in `initialize'
     # /Users/admin/.rvm/gems/ruby-2.1.1@mygem/gems/webmock-1.21.0/lib/webmock/util/json.rb:24:in `new'
     # /Users/admin/.rvm/gems/ruby-2.1.1@mygem/gems/webmock-1.21.0/lib/webmock/util/json.rb:24:in `convert_json_to_yaml'
     # /Users/admin/.rvm/gems/ruby-2.1.1@mygem/gems/webmock-1.21.0/lib/webmock/util/json.rb:12:in `parse'
     # /Users/admin/.rvm/gems/ruby-2.1.1@mygem/gems/webmock-1.21.0/lib/webmock/request_pattern.rb:235:in `body_as_hash'
     # /Users/admin/.rvm/gems/ruby-2.1.1@mygem/gems/webmock-1.21.0/lib/webmock/request_pattern.rb:218:in `matches?'
     # /Users/admin/.rvm/gems/ruby-2.1.1@mygem/gems/webmock-1.21.0/lib/webmock/request_pattern.rb:34:in `matches?'
     # /Users/admin/.rvm/gems/ruby-2.1.1@mygem/gems/webmock-1.21.0/lib/webmock/stub_registry.rb:58:in `block in request_stub_for'
     # /Users/admin/.rvm/gems/ruby-2.1.1@mygem/gems/webmock-1.21.0/lib/webmock/stub_registry.rb:57:in `each'
     # /Users/admin/.rvm/gems/ruby-2.1.1@mygem/gems/webmock-1.21.0/lib/webmock/stub_registry.rb:57:in `detect'
     # /Users/admin/.rvm/gems/ruby-2.1.1@mygem/gems/webmock-1.21.0/lib/webmock/stub_registry.rb:57:in `request_stub_for'
     # /Users/admin/.rvm/gems/ruby-2.1.1@mygem/gems/webmock-1.21.0/lib/webmock/stub_registry.rb:50:in `response_for_request'
     # /Users/admin/.rvm/gems/ruby-2.1.1@mygem/gems/webmock-1.21.0/lib/webmock/http_lib_adapters/patron_adapter.rb:22:in `handle_request'
     # /Users/admin/.rvm/gems/ruby-2.1.1@mygem/gems/patron-0.4.19.beta.2/lib/patron/session.rb:224:in `request'
     # /Users/admin/.rvm/gems/ruby-2.1.1@mygem/gems/faraday-0.8.9/lib/faraday/adapter/patron.rb:33:in `call'
     # /Users/admin/.rvm/gems/ruby-2.1.1@mygem/gems/faraday-0.8.9/lib/faraday/connection.rb:253:in `run_request'
     # /Users/admin/.rvm/gems/ruby-2.1.1@mygem/gems/faraday-0.8.9/lib/faraday/connection.rb:118:in `post'
```
It could be caused by wrong usage of HashIncludingMatcher matching body:
with(:body => hash_including(_some hash here_))
It fails when request has nil body because it tries to create StringScanner for nil.
If it's a bug, I can write spec and PR for that.

**Comment by bombazook** [comment]
Also noticed that this issue appears because patron adapter does not create signature correctly here:
https://github.com/bblimke/webmock/blob/master/lib/webmock/http_lib_adapters/patron_adapter.rb#L74
because `req.action` returns "POST" which prevents code under if statement to set _request_body_.
It looks like it would be better to change it to something like 
```['put', 'post'].include?(req.action.to_s.downcase)```

**Comment by bblimke** [comment]
@bombazook it's definitely a bug. Thank you for reporting it.

PR would be welcome!
