### ISSUE TITLE
Comparison of Array with Array fails when mocking array of objects in query params

### ISSUE THREAD

**Issue by DVG** [bblimke/webmock#525]
I have a query object that looks like:

```ruby
{
  foos: [
    {bar_id: "1", bar_value: "bar"},
    {bar_id: "2", bar_value: "baz"}
  ]
}
```

When I attempt to mock this request by doing

```ruby
stub_request(:get, some_url).with(query: query)
```

I get 

```shell
ArgumentError:
       comparison of Array with Array failed
     # /webmock-1.20.3/lib/webmock/util/query_mapper.rb:199:in `sort!'
     # //webmock-1.20.3/lib/webmock/util/query_mapper.rb:199:in `values_to_query'
     # /webmock-1.20.3/lib/webmock/request_pattern.rb:174:in `add_query_params'
     # /webmock-1.20.3/lib/webmock/request_pattern.rb:56:in `assign_options'
     # /webmock-1.20.3/lib/webmock/request_pattern.rb:24:in `with'
     # /webmock-1.20.3/lib/webmock/request_stub.rb:13:in `with'
```

**Comment by davidbegin** [comment]
Thanks for submitting this issue, however this has been updated on master, https://github.com/bblimke/webmock/commit/2ae77f60b0a6edbeec9042504ebbfe821adcc34f

We just have not release a new version yet. Which will hopefully be soon.
