### ISSUE TITLE
undefined method 'sysread' for class 'StringIO' (NameError)

### ISSUE THREAD

**Issue by mmaa** [bblimke/webmock#565]
When requiring webmock in spec_helper, I get the following exception:
```
2.2.3/lib/ruby/gems/2.2.0/gems/webmock-1.22.3/lib/webmock/response.rb:5:in 'alias_method': undefined method 'sysread' for class 'StringIO' (NameError)
  from 2.2.3/lib/ruby/gems/2.2.0/gems/webmock-1.22.3/lib/webmock/response.rb:5:in '<class:StringIO>'
  from 2.2.3/lib/ruby/gems/2.2.0/gems/webmock-1.22.3/lib/webmock/response.rb:4:in '<top (required)>'
  from 2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in 'require'
  from 2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in 'require'
  from 2.2.3/lib/ruby/gems/2.2.0/gems/webmock-1.22.3/lib/webmock.rb:27:in '<top (required)>'
  from 2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in 'require'
  from 2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in 'rescue in require'
  from 2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in 'require'
  from [...]/spec/spec_helper.rb:1:in '<top (required)>'
  from 2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in 'require'
  from 2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in 'require'
  from [...]/spec/parsers/line_item_spec.rb:1:in '<top (required)>'
  from 2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1361:in 'load'
  from 2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1361:in 'block in load_spec_files'
  from 2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1359:in 'each'
  from 2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1359:in 'load_spec_files'
  from 2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:102:in 'setup'
  from 2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:88:in 'run'
  from 2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:73:in 'run'
  from 2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:41:in 'invoke'
  from 2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/exe/rspec:4:in '<top (required)>'
  from 2.2.3/bin/rspec:23:in 'load'
  from 2.2.3/bin/rspec:23:in '<main>'
```

I'm using ruby 2.2.3, webmock 1.22.3, and rsepc 3.4.1. Is this a known issue? What's a possible workaround? I'm not really sure where to begin.

**Comment by davidbegin** [comment]
Thanks for creating this issue. To my knowledge this is not a known error.

It looks like this line was added for Ruby 1.9.2 support, and is not needed by later versions, so I will work on a fix.

**Comment by davidbegin** [comment]
@mmaa I am working on a fix here: https://github.com/bblimke/webmock/issues/565

**Comment by mmaa** [comment]
Fixed! Thanks for the quick response!

Any idea when this might get released?

**Comment by davidbegin** [comment]
@mmaa I was actually working on a release today, but I'm still working out getting my permissions worked out.

So I think we will just skip 1.22.4 and include this fix and release straight to 1.22.5. Hopefully today, but might not be until tomorrow

**Comment by mmaa** [comment]
Excellent, and thanks again. I really appreciate it.

**Comment by davidbegin** [comment]
No problem, thanks for submitting an issue! 1.22.5 is now out!
