### ISSUE TITLE
RuntimeError - can't add a new key into hash during iteration

### ISSUE THREAD

**Issue by burgalon** [bblimke/webmock#606]
```
RuntimeError - can't add a new key into hash during iteration
    /Users/burg/.rvm/gems/ruby-2.3.0/gems/webmock-1.22.3/lib/webmock/util/hash_counter.rb:15:in `block in put'
    /Users/burg/.rvm/gems/ruby-2.3.0/gems/webmock-1.22.3/lib/webmock/util/hash_counter.rb:14:in `synchronize'
    /Users/burg/.rvm/gems/ruby-2.3.0/gems/webmock-1.22.3/lib/webmock/util/hash_counter.rb:14:in `put'
    /Users/burg/.rvm/gems/ruby-2.3.0/gems/webmock-1.22.3/lib/webmock/http_lib_adapters/net_http.rb:77:in `request'
    /Users/burg/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:1378:in `send_request'
    /Users/burg/git/infinidat/infinibox-webgui2/webgui/test/spec/support/sinatra_proxy.rb:26:in `block in <class:SinatraProxy>'
```

The above is being caused by RequestRegistry.times_executed which iterates on the hash while some other thread might be setting it.

Working on a pull request

**Comment by grosscr** [comment]
Is there a fix coming for this? I've run into this issue as well.
