### ISSUE TITLE
"Unregistered request" output truncated

### ISSUE THREAD

**Issue by Vanders** [bblimke/webmock#709]
I have a problem where a previously working Webmock stub is now failing. However the output from RSpec is truncating the unregistered request output, making it impossible for me to understand the delta between the unregistered request & the stub I've configured in the test. For example, when running RSpec:
```  1) Cyclid::Cli::Job using the "job" commands #submit submits a JSON job
     Failure/Error: expect{ subject.submit('test-job.json') }.to_not raise_error

       expected no Exception, got #<WebMock::NetConnectNotAllowedError: Real HTTP connections are disabled. Unregistered request: POST ...n(status: 200, body: "", headers: {})

       ============================================================> with backtrace:
         # ./vendor/bundle/ruby/2.3.0/gems/webmock-3.0.1/lib/webmock/http_lib_adapters/net_http.rb:114:in `request'
         # ./lib/cyclid/client/api.rb:85:in `api_request'
         # ./lib/cyclid/client/api.rb:46:in `api_raw_post'
         # ./lib/cyclid/client.rb:95:in `method_missing'
         # ./lib/cyclid/client/job.rb:37:in `job_submit'
         # ./lib/cyclid/cli/job.rb:43:in `submit'
         # ./spec/cli/job_spec.rb:28:in `block (5 levels) in <top (required)>'
         # ./spec/cli/job_spec.rb:28:in `block (4 levels) in <top (required)>'
     # ./spec/cli/job_spec.rb:28:in `block (4 levels) in <top (required)>'
```

I'm using Ruby 2.3.1 with Webmock 3.0.1.

**Comment by bblimke** [comment]
It's not Webmock that is truncating the output. Perhaps it's Rspec?

**Comment by KDGundermann** [comment]
Yes its RSpec, 
see: https://github.com/rspec/rspec-expectations/issues/991
