### ISSUE TITLE
YAML deserialization of serialized WebMockHttpClient fails

### ISSUE THREAD

**Issue by ericroberts** [bblimke/webmock#729]
If I open an irb prompt and do this:

```
> require "webmock"
> WebMock.enable!
> YAML.load EventMachine::WebMockHttpClient.new(nil, nil).to_yaml
```

I get this:

```
ArgumentError: undefined class/module EventMachine::HttpClient::CookieJar
	from /opt/rubies/2.4.2/lib/ruby/2.4.0/psych/class_loader.rb:54:in `path2class'
	from /opt/rubies/2.4.2/lib/ruby/2.4.0/psych/class_loader.rb:54:in `resolve'
	from /opt/rubies/2.4.2/lib/ruby/2.4.0/psych/class_loader.rb:46:in `find'
	from /opt/rubies/2.4.2/lib/ruby/2.4.0/psych/class_loader.rb:28:in `load'
	from /opt/rubies/2.4.2/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:396:in `resolve_class'
	from /opt/rubies/2.4.2/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:208:in `visit_Psych_Nodes_Mapping'
	from /opt/rubies/2.4.2/lib/ruby/2.4.0/psych/visitors/visitor.rb:16:in `visit'
	from /opt/rubies/2.4.2/lib/ruby/2.4.0/psych/visitors/visitor.rb:6:in `accept'
	from /opt/rubies/2.4.2/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:32:in `accept'
	from /opt/rubies/2.4.2/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:338:in `block in revive_hash'
	from /opt/rubies/2.4.2/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:336:in `each'
	from /opt/rubies/2.4.2/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:336:in `each_slice'
	from /opt/rubies/2.4.2/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:336:in `revive_hash'
	from /opt/rubies/2.4.2/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:374:in `revive'
	from /opt/rubies/2.4.2/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:208:in `visit_Psych_Nodes_Mapping'
	from /opt/rubies/2.4.2/lib/ruby/2.4.0/psych/visitors/visitor.rb:16:in `visit'
	from /opt/rubies/2.4.2/lib/ruby/2.4.0/psych/visitors/visitor.rb:6:in `accept'
	from /opt/rubies/2.4.2/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:32:in `accept'
	from /opt/rubies/2.4.2/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:311:in `visit_Psych_Nodes_Document'
	from /opt/rubies/2.4.2/lib/ruby/2.4.0/psych/visitors/visitor.rb:16:in `visit'
	from /opt/rubies/2.4.2/lib/ruby/2.4.0/psych/visitors/visitor.rb:6:in `accept'
	from /opt/rubies/2.4.2/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:32:in `accept'
	from /opt/rubies/2.4.2/lib/ruby/2.4.0/psych/nodes/node.rb:38:in `to_ruby'
	from /opt/rubies/2.4.2/lib/ruby/2.4.0/psych.rb:253:in `load'
	from (irb):7
	from /opt/rubies/2.4.2/bin/irb:11:in `<main>'
```

This causes problems as I am trying to store a client in a serialized rails column, and am unable to do so in my test environment. It works as expected in production, which leads me to believe the problem is with this gem.

**Comment by bblimke** [comment]
Sorry, but why would you try to serialize a http client instance? :)

**Comment by ericroberts** [comment]
We're storing error responses in some cases and that includes serializing the client.

**Comment by oliakremmyda** [comment]
Hi, 

I have found a similar case here https://stackoverflow.com/questions/13750342/yamlload-raises-undefined-class-module-error.
From the comments seems that `psych` cannot find the definition of `EventMachine::HttpClient::CookieJar` when you are calling `YAML.load`. 

I have tried the following code and is working:
```
require 'webmock'
include WebMock::API
WebMock.enable!

class EventMachine::HttpClient::CookieJar; end
YAML.load EventMachine::WebMockHttpClient.new(nil, nil).to_yaml
```
I don't know, though, if an extra `require` should be added in webmock for your code to work.
