### ISSUE TITLE
Proxy gets down after single failure

### ISSUE THREAD

**Issue by printercu** [bblimke/webmock#730]
Hi!

I'm getting `Failed to load resource: net::ERR_PROXY_CONNECTION_FAILED` in all subsequent specs after one of them failed with:

```
WebMock::NetConnectNotAllowedError:
            Real HTTP connections are disabled ...
```

My config is just:

```ruby
require 'webmock/rspec'
WebMock.disable_net_connect!(
  allow_localhost: true,
  allow: 'chrome-devtools-frontend.appspot.com',
)
```

**Comment by bblimke** [comment]
@printercu can you please provide a sample code to replicate the issue?

**Comment by printercu** [comment]
Thanks for fast feedback!

Here are 2 equal examples separated with failing spec. Run it with `rspec --order defined` to prevent shuffling.

```ruby
RSpec.describe 'test', js: true do
  # Page has `img src='http://external.example.com/image.png'`
  before { stub_request(:get, %r{external.example.com}) }
  after { assert_no_js_errors }

  class JavaScriptError < StandardError; end

  def assert_no_js_errors
    errors = page.driver.browser.manage.logs.get(:browser).
      select { |e| e.level == 'SEVERE' && e.message.present? }.
      map(&:message).
      to_a
    raise JavaScriptError, errors.join("\n\n") if errors.any?
  end

  scenario 'stubbed-1' do
    visit '/'
    sleep(1) # wait for images
  end

  scenario 'failing' do
    visit '/'
    sleep(1) # wait for images
    WebMock.reset!
    visit '/'
    sleep(1) # wait for images
  end

  scenario 'stubbed-2' do
    visit '/'
    sleep(1) # wait for images
  end
end
```

For me it results in:
<details><summary>Expand</summary>

```
  stubbed-1
  failing (FAILED - 1)
  stubbed-2 (FAILED - 2)

Failures:

  1) test failing
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: raise WebMock::NetConnectNotAllowedError.new(request_signature)

          WebMock::NetConnectNotAllowedError:
            Real HTTP connections are disabled. Unregistered request: GET http://external.example.com/image.png with headers {'Accept'=>'image/webp,image/apng,image/*,*/*;q=0.8', 'Accept-Language'=>'en-GB,en-US;q=0.9,en;q=0.8', 'Host'=>'external.example.com', 'Proxy-Connection'=>'keep-alive', 'Referer'=>'http://127.0.0.1:55524/', 'User-Agent'=>'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36'}

            You can stub this request with the following snippet:

            stub_request(:get, "http://external.example.com/image.png").
              with(headers: {'Accept'=>'image/webp,image/apng,image/*,*/*;q=0.8', 'Accept-Language'=>'en-GB,en-US;q=0.9,en;q=0.8', 'Host'=>'external.example.com', 'Proxy-Connection'=>'keep-alive', 'Referer'=>'http://127.0.0.1:55524/', 'User-Agent'=>'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36'}).
              to_return(status: 200, body: "", headers: {})

            ============================================================
          # /Users/max/.rvm/gems/ruby-2.4.1/gems/webmock-3.1.0/lib/webmock/http_lib_adapters/em_http_request_adapter.rb:74:in `activate_connection'
          # /Users/max/.rvm/gems/ruby-2.4.1/gems/em-http-request-1.1.5/lib/em-http/http_connection.rb:92:in `setup_request'
          # (eval):5:in `get'
          # /Users/max/.rvm/gems/ruby-2.4.1/gems/puffing-billy-0.11.0/lib/billy/handlers/proxy_handler.rb:28:in `handle_request'
          # /Users/max/.rvm/gems/ruby-2.4.1/gems/puffing-billy-0.11.0/lib/billy/handlers/request_handler.rb:19:in `block in handle_request'
          # /Users/max/.rvm/gems/ruby-2.4.1/gems/puffing-billy-0.11.0/lib/billy/handlers/request_handler.rb:18:in `each'
          # /Users/max/.rvm/gems/ruby-2.4.1/gems/puffing-billy-0.11.0/lib/billy/handlers/request_handler.rb:18:in `handle_request'
          # /Users/max/.rvm/gems/ruby-2.4.1/gems/puffing-billy-0.11.0/lib/billy/proxy_connection.rb:61:in `block in handle_request'
          # /Users/max/.rvm/gems/ruby-2.4.1/gems/em-synchrony-1.0.6/lib/em-synchrony.rb:30:in `block in synchrony'

     1.2) Failure/Error: raise JavaScriptError, errors.join("\n\n") if errors.any?

          JavaScriptError:
            http://external.example.com/image.png - Failed to load resource: net::ERR_PROXY_CONNECTION_FAILED
          # ./spec/features/site/test_spec.rb:13:in `assert_no_js_errors'
          # ./spec/features/site/test_spec.rb:4:in `block (2 levels) in <top (required)>'

  2) test stubbed-2
     Failure/Error: raise JavaScriptError, errors.join("\n\n") if errors.any?

     JavaScriptError:
       http://127.0.0.1:55524/ - Failed to load resource: net::ERR_PROXY_CONNECTION_FAILED

       http://127.0.0.1:55524/ - Failed to load resource: net::ERR_PROXY_CONNECTION_FAILED
     # ./spec/features/site/test_spec.rb:13:in `assert_no_js_errors'
     # ./spec/features/site/test_spec.rb:4:in `block (2 levels) in <top (required)>'

Finished in 6.41 seconds (files took 5.04 seconds to load)
3 examples, 2 failures

Failed examples:

rspec ./spec/features/site/test_spec.rb:21 # test failing
rspec ./spec/features/site/test_spec.rb:29 # test stubbed-2
```

</details>

I use chromedriver.

**Comment by bblimke** [comment]
Thanks.

I meant code sample that I can just run on my own, without any additional programming.

I suspect it may be related to your test environment.

What do you expect to run on port 55524? Is there any change that the server which is supposed to run there is getting killed upon an error raised by WebMock from the spec?

**Comment by bblimke** [comment]
Please note that the net::ERR_PROXY_CONNECTION_FAILED error doesn't seem to be related to webmock. Looks like it's a javascript error raised by the browser. Nothing to do with Ruby, therefore nothing to do with WebMock on it's own.

**Comment by printercu** [comment]
Seems like it's [puffing-billy](https://github.com/oesmith/puffing-billy) gem issue. Just tried with similar spec with `Net::HTTP` and everything worked.

Sorry for false issue.
