### ISSUE TITLE
Implicit Conversion Error when POSTing to stubbed request

### ISSUE THREAD

**Issue by DannyJF** [bblimke/webmock#735]
I'm getting the following error when attempting to post data to a stubbed request:
```
no implicit conversion of ActiveSupport::HashWithIndifferentAccess into String
/Users/dfre/.rvm/gems/ruby-2.4.3/gems/webmock-3.1.1/lib/webmock/util/json.rb:27:in `initialize'
/Users/dfre/.rvm/gems/ruby-2.4.3/gems/webmock-3.1.1/lib/webmock/util/json.rb:27:in `new'
/Users/dfre/.rvm/gems/ruby-2.4.3/gems/webmock-3.1.1/lib/webmock/util/json.rb:27:in `convert_json_to_yaml'
/Users/dfre/.rvm/gems/ruby-2.4.3/gems/webmock-3.1.1/lib/webmock/util/json.rb:14:in `parse'
/Users/dfre/.rvm/gems/ruby-2.4.3/gems/webmock-3.1.1/lib/webmock/request_pattern.rb:264:in `body_as_hash'
/Users/dfre/.rvm/gems/ruby-2.4.3/gems/webmock-3.1.1/lib/webmock/request_pattern.rb:246:in `matches?'
/Users/dfre/.rvm/gems/ruby-2.4.3/gems/webmock-3.1.1/lib/webmock/request_pattern.rb:38:in `matches?'
/Users/dfre/.rvm/gems/ruby-2.4.3/gems/webmock-3.1.1/lib/webmock/stub_registry.rb:58:in `block in request_stub_for'
/Users/dfre/.rvm/gems/ruby-2.4.3/gems/webmock-3.1.1/lib/webmock/stub_registry.rb:57:in `each'
/Users/dfre/.rvm/gems/ruby-2.4.3/gems/webmock-3.1.1/lib/webmock/stub_registry.rb:57:in `detect'
/Users/dfre/.rvm/gems/ruby-2.4.3/gems/webmock-3.1.1/lib/webmock/stub_registry.rb:57:in `request_stub_for'
/Users/dfre/.rvm/gems/ruby-2.4.3/gems/webmock-3.1.1/lib/webmock/stub_registry.rb:50:in `response_for_request'
/Users/dfre/.rvm/gems/ruby-2.4.3/gems/webmock-3.1.1/lib/webmock/http_lib_adapters/net_http.rb:79:in `request'
/Users/dfre/.rvm/gems/ruby-2.4.3/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:80:in `perform_request'
/Users/dfre/.rvm/gems/ruby-2.4.3/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:38:in `block in call'
/Users/dfre/.rvm/gems/ruby-2.4.3/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
/Users/dfre/.rvm/gems/ruby-2.4.3/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:33:in `call'
/Users/dfre/.rvm/gems/ruby-2.4.3/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:31:in `call'
/Users/dfre/.rvm/gems/ruby-2.4.3/gems/faraday_middleware-0.12.2/lib/faraday_middleware/instrumentation.rb:26:in `block in call'
/Users/dfre/.rvm/gems/ruby-2.4.3/gems/activesupport-5.1.4/lib/active_support/notifications.rb:168:in `instrument'
/Users/dfre/.rvm/gems/ruby-2.4.3/gems/faraday_middleware-0.12.2/lib/faraday_middleware/instrumentation.rb:25:in `call'
/Users/dfre/.rvm/gems/ruby-2.4.3/gems/faraday-0.12.2/lib/faraday/rack_builder.rb:141:in `build_response'
/Users/dfre/.rvm/gems/ruby-2.4.3/gems/faraday-0.12.2/lib/faraday/connection.rb:386:in `run_request'
/Users/dfre/.rvm/gems/ruby-2.4.3/gems/faraday-0.12.2/lib/faraday/connection.rb:186:in `post'
```
This is occurring when when I POST, however it only is thrown when I've set up a body in the mock call.

This finishes (the test correct fails):
```
stub_request(:post, "https://domain.com/path")
        .with(headers: basic_headers)
        .to_return(status: 200, body: { token: '1234' }.to_json)
post "path", params: { status: 'reboot' }, headers: basic_headers }
```

This should succeed but throws the above stacktrace:
```
stub_request(:post, "https://domain.com/path")
        .with('body' => {"status"=>"reboot"}), headers: basic_headers)
        .to_return(status: 200, body: '')
post "path", params: { status: 'reboot' }, headers: basic_headers }
````

My best guess is that there's a weird interaction with Faraday and webmock?

I'm still researching to get more information.

**Comment by DannyJF** [comment]
I had a bug in my code that should have been converting the has to a json string before sending it to faraday. I'm Not sure if this is valid or not, but if no no else is seeing this i'll close this out as user error.
