### ISSUE TITLE
Undefined method `read_nonblock' for string

### ISSUE THREAD

**Issue by jaimeiniesta** [bblimke/webmock#743]
I'm getting random errors when using webmock, loading raw responses from files, like this one:

```
  1) MetaInspector should get the title from the head section
     Failure/Error: stub_request(:get, "http://alazan.com/websolution.asp").to_return(fixture_file("alazan_websolution.response"))

     NoMethodError:
       undefined method `read_nonblock' for #<String:0x007ff205b16850>
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/webmock-3.3.0/lib/webmock/response.rb:124:in `read_raw_response'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/webmock-3.3.0/lib/webmock/response.rb:18:in `initialize'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/webmock-3.3.0/lib/webmock/response.rb:10:in `new'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/webmock-3.3.0/lib/webmock/response.rb:10:in `response_for'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/webmock-3.3.0/lib/webmock/request_stub.rb:21:in `block in to_return'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/webmock-3.3.0/lib/webmock/request_stub.rb:21:in `map'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/webmock-3.3.0/lib/webmock/request_stub.rb:21:in `to_return'
     # ./spec/spec_helper.rb:17:in `block (2 levels) in <top (required)>'
```

Most specs run fine but then it crashes into that, and all the next specs will fail exactly like that.

This fails both in my dev machine, as in Travis:

https://travis-ci.org/jaimeiniesta/metainspector/jobs/337621342

This issue seems related to https://github.com/bblimke/webmock/issues/558

**Comment by jaimeiniesta** [comment]
You can see the error happening in this branch:

https://github.com/jaimeiniesta/metainspector/tree/failing-mocks

**Comment by bblimke** [comment]
@jaimeiniesta could you please run rspec with -b option, to get the full stacktrace.

**Comment by jaimeiniesta** [comment]
@bblimke sure, here it goes:

```
  1) MetaInspector should get the title from the head section
     Failure/Error: stub_request(:get, "http://alazan.com/websolution.asp").to_return(fixture_file("alazan_websolution.response"))

     NoMethodError:
       undefined method `read_nonblock' for #<String:0x007fdfb1b03c48>
     # /Users/jaime/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/protocol.rb:172:in `rbuf_fill'
     # /Users/jaime/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/protocol.rb:154:in `readuntil'
     # /Users/jaime/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/protocol.rb:164:in `readline'
     # /Users/jaime/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http/response.rb:40:in `read_status_line'
     # /Users/jaime/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http/response.rb:29:in `read_new'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/webmock-3.3.0/lib/webmock/response.rb:124:in `read_raw_response'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/webmock-3.3.0/lib/webmock/response.rb:18:in `initialize'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/webmock-3.3.0/lib/webmock/response.rb:10:in `new'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/webmock-3.3.0/lib/webmock/response.rb:10:in `response_for'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/webmock-3.3.0/lib/webmock/request_stub.rb:21:in `block in to_return'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/webmock-3.3.0/lib/webmock/request_stub.rb:21:in `map'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/webmock-3.3.0/lib/webmock/request_stub.rb:21:in `to_return'
     # ./spec/spec_helper.rb:17:in `block (2 levels) in <top (required)>'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:447:in `instance_exec'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:447:in `instance_exec'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:350:in `run'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:509:in `block in run_owned_hooks_for'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:508:in `each'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:508:in `run_owned_hooks_for'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:595:in `block in run_example_hooks_for'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:594:in `reverse_each'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:594:in `run_example_hooks_for'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:464:in `run'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:494:in `run_before_example'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:253:in `block in run'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:466:in `block in run'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:604:in `run_around_example_hooks_for'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:466:in `run'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:251:in `run'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:628:in `block in run_examples'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:624:in `map'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:624:in `run_examples'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:590:in `run'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `block (3 levels) in run_specs'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `map'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `block (2 levels) in run_specs'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1926:in `with_suite_hooks'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:113:in `block in run_specs'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:79:in `report'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:112:in `run_specs'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:87:in `run'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.7.1/exe/rspec:4:in `<top (required)>'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/bin/rspec:22:in `load'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/bin/rspec:22:in `<main>'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
     # /Users/jaime/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by jaimeiniesta** [comment]
And here's a fail from Travis:

```
  1) MetaInspector should get the title from the head section
     Failure/Error: stub_request(:get, "http://alazan.com/websolution.asp").to_return(fixture_file("alazan_websolution.response"))
     
     NoMethodError:
       undefined method `read_nonblock' for #<String:0x00000003d6dcd0>
     # /home/travis/.rvm/rubies/ruby-2.2.9/lib/ruby/2.2.0/net/protocol.rb:153:in `rbuf_fill'
     # /home/travis/.rvm/rubies/ruby-2.2.9/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
     # /home/travis/.rvm/rubies/ruby-2.2.9/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'
     # /home/travis/.rvm/rubies/ruby-2.2.9/lib/ruby/2.2.0/net/http/response.rb:39:in `read_status_line'
     # /home/travis/.rvm/rubies/ruby-2.2.9/lib/ruby/2.2.0/net/http/response.rb:28:in `read_new'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/webmock-3.3.0/lib/webmock/response.rb:124:in `read_raw_response'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/webmock-3.3.0/lib/webmock/response.rb:18:in `initialize'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/webmock-3.3.0/lib/webmock/response.rb:10:in `new'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/webmock-3.3.0/lib/webmock/response.rb:10:in `response_for'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/webmock-3.3.0/lib/webmock/request_stub.rb:21:in `block in to_return'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/webmock-3.3.0/lib/webmock/request_stub.rb:21:in `map'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/webmock-3.3.0/lib/webmock/request_stub.rb:21:in `to_return'
     # ./spec/spec_helper.rb:17:in `block (2 levels) in <top (required)>'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:447:in `instance_exec'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:447:in `instance_exec'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:350:in `run'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:509:in `block in run_owned_hooks_for'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:508:in `each'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:508:in `run_owned_hooks_for'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:595:in `block in run_example_hooks_for'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:594:in `reverse_each'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:594:in `run_example_hooks_for'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:464:in `run'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:494:in `run_before_example'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:253:in `block in run'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:466:in `block in run'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:604:in `run_around_example_hooks_for'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:466:in `run'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:251:in `run'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:628:in `block in run_examples'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:624:in `map'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:624:in `run_examples'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:590:in `run'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `block (3 levels) in run_specs'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `map'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `block (2 levels) in run_specs'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1926:in `with_suite_hooks'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:113:in `block in run_specs'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:79:in `report'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:112:in `run_specs'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:87:in `run'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
     # /home/travis/.rvm/gems/ruby-2.2.9/gems/rspec-core-3.7.1/exe/rspec:4:in `<top (required)>'
     # /home/travis/.rvm/gems/ruby-2.2.9/bin/rspec:23:in `load'
     # /home/travis/.rvm/gems/ruby-2.2.9/bin/rspec:23:in `<main>'
     # /home/travis/.rvm/gems/ruby-2.2.9/bin/ruby_executable_hooks:15:in `eval'
     # /home/travis/.rvm/gems/ruby-2.2.9/bin/ruby_executable_hooks:15:in `<main>'
```

Here's the Travis build:

https://travis-ci.org/jaimeiniesta/metainspector/builds/339822348

**Comment by bblimke** [comment]
@jaimeiniesta the problem is due to the redirections state, leaving a dirty state https://github.com/jaimeiniesta/metainspector/blob/400d71ba680c48c5c2df29688c68b3d68c3c8435/spec/meta_inspector/redirections_spec.rb#L22-L23 with WebMock being disabled.

It looks like WebMock doesn't handle creating stubbed responses from raw responses,
when WebMock is disabled, which has probably not been spotted by anyone before.

In the specs that fail, WebMock is simply disabled.

**Comment by jaimeiniesta** [comment]
Ah! Sorry, I forgot to remove these lines - we were previously using FakeWeb for our suite, but we used WebMock for the redirections specs only, that's why they're enabled and then disabled. But now our entire suite uses WebMock, so it should always be enabled.

I'll close this issue now, maybe this detail can be added to WebMock, like being able to define stubs even when it's disabled, or rejecting them with a more meaningful response, but regarding this case it's all green now, thanks!
