### ISSUE TITLE
Stubbing a put with a hash body fails. 

### ISSUE THREAD

**Issue by jcoyne** [bblimke/webmock#838]
When I first make this request:

```ruby
          resp = connection.put do |req|
            req.url 'v1/objects/druid:1234'
            req.body = { constituent_ids: ["druid:child1", "druid:child2"] }
          end
```

I get this notice from webmock:

```
     WebMock::NetConnectNotAllowedError:
       Real HTTP connections are disabled. Unregistered request: PUT https://dor-services.example.com/v1/objects/druid:1234 with body '{:constituent_ids=>["druid:child1", "druid:child2"]}' with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'User-Agent'=>'dor-services-client 1.11.0'}

       You can stub this request with the following snippet:

       stub_request(:put, "https://dor-services.example.com/v1/objects/druid:1234").
         with(
           body: {"constituent_ids"=>["druid:child1", "druid:child2"]},
           headers: {
       	  'Accept'=>'*/*',
       	  'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3',
       	  'User-Agent'=>'dor-services-client 1.11.0'
           }).
         to_return(status: 200, body: "", headers: {})

       ============================================================
```

Then when I add that and re-run I get:

```
     NoMethodError:
       undefined method `split' for {:constituent_ids=>["druid:child1", "druid:child2"]}:Hash
     # /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/webmock-3.4.2/lib/webmock/util/query_mapper.rb:73:in `collect_query_parts'
     # /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/webmock-3.4.2/lib/webmock/util/query_mapper.rb:54:in `query_to_values'
     # /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/webmock-3.4.2/lib/webmock/request_pattern.rb:277:in `body_as_hash'
     # /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/webmock-3.4.2/lib/webmock/request_pattern.rb:255:in `matches?'
     # /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/webmock-3.4.2/lib/webmock/request_pattern.rb:38:in `matches?'
     # /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/webmock-3.4.2/lib/webmock/stub_registry.rb:58:in `block in request_stub_for'
     # /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/webmock-3.4.2/lib/webmock/stub_registry.rb:57:in `each'
     # /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/webmock-3.4.2/lib/webmock/stub_registry.rb:57:in `detect'
     # /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/webmock-3.4.2/lib/webmock/stub_registry.rb:57:in `request_stub_for'
     # /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/webmock-3.4.2/lib/webmock/stub_registry.rb:50:in `response_for_request'
     # /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/webmock-3.4.2/lib/webmock/http_lib_adapters/net_http.rb:79:in `request'
     # /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:87:in `perform_request'
     # /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:43:in `block in call'
     # /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
     # /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:38:in `call'
```

Using (string key) doesn't seem to change the outcome.
```
            req.body = { 'constituent_ids' => ["druid:child1", "druid:child2"] }
```

**Comment by bblimke** [comment]
@jcoyne what is supposed to be the format of the body? currently is't Hash#to_s . perhaps you should serialize it to json before making the request?

**Comment by jcoyne** [comment]
Sorry, this was my fault. It works when I added the correct Faraday middleware:
```
          builder.use Faraday::Request::UrlEncoded
```
