### ISSUE TITLE
Ruby 3.0 test failures

### ISSUE THREAD

**Issue by voxik** [bblimke/webmock#924]
There are test failures [[1]] due to webrick being removed from Ruby 3.0:

~~~
$ bundle exec rake
/home/travis/.rvm/rubies/ruby-head/bin/ruby -I/home/travis/.rvm/gems/ruby-head/gems/rspec-core-3.10.1/lib:/home/travis/.rvm/gems/ruby-head/gems/rspec-support-3.10.1/lib /home/travis/.rvm/gems/ruby-head/gems/rspec-core-3.10.1/exe/rspec --pattern spec/\*\*/\*_spec.rb -c -f progress -r ./spec/spec_helper.rb
An error occurred while loading ./spec/spec_helper.rb. - Did you mean?
                    rspec ./spec/unit/response_spec.rb
Failure/Error: require 'webrick'
LoadError:
  cannot load such file -- webrick
# ./spec/support/webmock_server.rb:1:in `require'
# ./spec/support/webmock_server.rb:1:in `<top (required)>'
# ./spec/spec_helper.rb:20:in `require'
# ./spec/spec_helper.rb:20:in `<top (required)>'
No examples found.
~~~

[1]: https://travis-ci.org/github/bblimke/webmock/jobs/754267284

**Comment by voxik** [comment]
It seems that the only place, where WEBrick is used is in spec/support/webmock_server.rb, so it should probably be just development dependency. I'll try to open PR.
