### ISSUE TITLE
`hash_including` matcher breaks `WebMock::Util::Headers.normalize_headers`

### ISSUE THREAD

**Issue by cosmicbuffalo** [bblimke/webmock#942]
came across this while attempting to put an expectation on a mocked request's headers

#### example test to reproduce:

```ruby

RSpec.describe "webmock broken normalize_headers test" do
  it 'should work' do
    WebMock.stub_request(:post, /foo/).to_return(body: proc{|_| {}.to_json })

    Faraday.post('http://www.foo.com', {foo: :bar}.to_json, "Content-Type" => 'application/json', "CUSTOM_HEADER" => "value")

    expect(WebMock).to have_requested(:post, 'http://www.foo.com').with(
      headers: hash_including({
        "CUSTOM_HEADER" => "value"
      })
    )
  end
end
```
#### This syntax looks like it should work fine judging by the examples in the readme:

<img width="866" alt="Screen Shot 2021-05-26 at 9 37 11 AM" src="https://user-images.githubusercontent.com/25158675/119680852-2af9e200-be07-11eb-8c23-475d51ade1f7.png">

#### But instead, the above example test spits out the following:
```ruby
Failures:

  1) webmock broken normalize_headers test should work
     Failure/Error:
       expect(WebMock).to have_requested(:post, 'http://www.foo.com').with(
         headers: hash_including({
           "CUSTOM_HEADER" => "value"
         })
       )
     
     NoMethodError:
       undefined method `map' for #<RSpec::Mocks::ArgumentMatchers::HashIncludingMatcher:0x0000000111c45dd0>
       Did you mean?  tap
     # ./vendor/bundle/ruby/2.6.0/gems/webmock-3.13.0/lib/webmock/util/headers.rb:11:in `normalize_headers'
     # ./vendor/bundle/ruby/2.6.0/gems/webmock-3.13.0/lib/webmock/request_pattern.rb:375:in `initialize'
     # ./vendor/bundle/ruby/2.6.0/gems/webmock-3.13.0/lib/webmock/request_pattern.rb:60:in `new'
     # ./vendor/bundle/ruby/2.6.0/gems/webmock-3.13.0/lib/webmock/request_pattern.rb:60:in `assign_options'
     # ./vendor/bundle/ruby/2.6.0/gems/webmock-3.13.0/lib/webmock/request_pattern.rb:28:in `with'
     # ./vendor/bundle/ruby/2.6.0/gems/webmock-3.13.0/lib/webmock/rspec/matchers/webmock_matcher.rb:35:in `with'
     # ./spec/lib/proxy/rspec_spec.rb:8:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.6.0/gems/webmock-3.13.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```

**Comment by bblimke** [comment]
@cosmicbuffalo hash_including doesn't work for headers, but matching headers behaves like hash_including by default.

**Comment by leodeoliveirasilva** [comment]
"matching headers behaves like hash_including by default" that is not working for me, when I try to match partially the headers, it does not work :(

**Comment by bblimke** [comment]
> "matching headers behaves like hash_including by default" that is not working for me, when I try to match partially the headers, it does not work :(

can you please provide an example if it's still relevant?

**Comment by mochetts** [comment]
Not working for me either. To reproduce:

```rb
describe "google" do
  it "test" do
    stub_request(:get, "google.com").with(headers: hash_including({})).to_return(body: "")
    Faraday.new.get("google.com") do |req|
      req.headers = { "Not-Included-In-Stub": "true" }
    end
    expect(WebMock).to have_requested(:get, 'google.com')
  end
end
```
