### ISSUE TITLE
net_http_connect_on_start: true breaks disable_net_connect! and stub_request?

### ISSUE THREAD

**Issue by dmolesUC** [bblimke/webmock#955]
## Summary

On the recommendation of the [Capybara docs](https://github.com/teamcapybara/capybara#gotchas), we've been setting `net_http_connect_on_start: true` in order to avoid having WebMock run us out of file handles during Selenium tests.

We've recently discovered, however, that this has the effect of allowing WebMock to work only if there's an actual, reachable service running on the specified host and port -- for a nonexistent hostname, or an unreachable host/port combination, net connections are not disabled and requests are not stubbed.

Per [this comment on #914](https://github.com/bblimke/webmock/issues/914#issuecomment-810134233) something like this is apparently expected behavior, but the [README](https://github.com/bblimke/webmock#connecting-on-nethttpstart) isn't very explicit. Maybe it's implied if you know a lot about `Net::HTTP` internals?

But I don't really care whether I have long-running connections, I just want to intercept requests, and not to run out of file handles. Is there any way around this?

## Steps to reproduce

Given the following test:

```ruby
require 'webmock/rspec'

describe :disable_net_connect! do
  shared_examples 'correctly' do |test_uri|
    it "intercepts Net::HTTP connections" do
      expect { Net::HTTP.get(test_uri) }.to raise_error(WebMock::NetConnectNotAllowedError)
    end

    it "can stub Net::HTTP requests" do
      http_status = 403
      stub_request(:get, test_uri).to_return(status: http_status)

      response = Net::HTTP.get_response(test_uri)
      expect(response.code).to eq(http_status.to_s)
    end
  end

  describe 'without net_http_connect_on_start' do
    around(:each) do |example|
      WebMock.disable_net_connect!
      example.run
      WebMock.allow_net_connect!
    end

    describe 'with real URI' do
      it_behaves_like 'correctly', URI.parse('http://example.org/')
    end

    describe 'with nonexistent URI' do
      it_behaves_like 'correctly', URI.parse('http://nonexistent-hostname:9999/')
    end

    describe 'with unreachable URI' do
      # NOTE: `other-local-hostname` is mapped to 127.0.0.1 in /etc/hosts
      it_behaves_like 'correctly', URI.parse('http://other-local-hostname:9999/')
    end
  end

  describe 'with net_http_connect_on_start' do
    around(:each) do |example|
      WebMock.disable_net_connect!(
        net_http_connect_on_start: true
      )
      example.run
      WebMock.allow_net_connect!
    end

    describe 'with real URI' do
      it_behaves_like 'correctly', URI.parse('http://example.org/')
    end

    describe 'with nonexistent URI' do
      it_behaves_like 'correctly', URI.parse('http://nonexistent-hostname:9999/')
    end

    describe 'with unreachable URI' do
      # NOTE: `other-local-hostname` is mapped to 127.0.0.1 in /etc/hosts
      it_behaves_like 'correctly', URI.parse('http://other-local-hostname:9999/')
    end
  end
end
```

## Expected

- All tests pass

## Actual

- without `net_http_connect_on_start`, all tests pass
- with `net_http_connect_on_start`:
  - tests with reachable host (`example.org`) pass
  - with nonexistent hostname:
    - "intercepts connections" test fails because `SocketError` is raised instead of `WebMock::NetConnectNotAllowedError`
    - "can stub requests" test fails because `SocketError` is raised instead of the stub being called
  - with valid hostname (`other-local-hostname`, mapped to 127.0.0.1 in `/etc/hosts`), but no service on the specified port: 
    - "intercepts connections" test fails because `Errno::ECONNREFUSED` is raised instead of `WebMock::NetConnectNotAllowedError`
    - "can stub requests" test fails because `Errno::ECONNREFUSED` is raised instead of the stub being called

```none
$ rspec ./disable_net_connect_spec.rb 
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
........FFFF

Failures:

  1) disable_net_connect! with net_http_connect_on_start with nonexistent URI behaves like correctly intercepts Net::HTTP connections
     Failure/Error: expect { Net::HTTP.get(test_uri) }.to raise_error(WebMock::NetConnectNotAllowedError)
     
       expected WebMock::NetConnectNotAllowedError, got #<SocketError: Failed to open TCP connection to nonexistent-hostname:9999 (getaddrinfo: nodename nor servname provided, or not known)> with backtrace:
         # /Users/david/.rvm/gems/ruby-2.7.2/gems/webmock-3.14.0/lib/webmock/http_lib_adapters/net_http.rb:148:in `start'
         # ./disable_net_connect_spec.rb:6:in `block (4 levels) in <top (required)>'
         # ./disable_net_connect_spec.rb:6:in `block (3 levels) in <top (required)>'
         # ./disable_net_connect_spec.rb:44:in `block (3 levels) in <top (required)>'
         # /Users/david/.rvm/gems/ruby-2.7.2/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
     Shared Example Group: "correctly" called from ./disable_net_connect_spec.rb:53
     # ./disable_net_connect_spec.rb:6:in `block (3 levels) in <top (required)>'
     # ./disable_net_connect_spec.rb:44:in `block (3 levels) in <top (required)>'
     # /Users/david/.rvm/gems/ruby-2.7.2/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  2) disable_net_connect! with net_http_connect_on_start with nonexistent URI behaves like correctly can stub Net::HTTP requests
     Failure/Error: response = Net::HTTP.get_response(test_uri)
     
     SocketError:
       Failed to open TCP connection to nonexistent-hostname:9999 (getaddrinfo: nodename nor servname provided, or not known)
     Shared Example Group: "correctly" called from ./disable_net_connect_spec.rb:53
     # /Users/david/.rvm/gems/ruby-2.7.2/gems/webmock-3.14.0/lib/webmock/http_lib_adapters/net_http.rb:148:in `start'
     # ./disable_net_connect_spec.rb:13:in `block (3 levels) in <top (required)>'
     # ./disable_net_connect_spec.rb:44:in `block (3 levels) in <top (required)>'
     # /Users/david/.rvm/gems/ruby-2.7.2/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # SocketError:
     #   getaddrinfo: nodename nor servname provided, or not known
     #   /Users/david/.rvm/gems/ruby-2.7.2/gems/webmock-3.14.0/lib/webmock/http_lib_adapters/net_http.rb:148:in `start'

  3) disable_net_connect! with net_http_connect_on_start with unreachable URI behaves like correctly intercepts Net::HTTP connections
     Failure/Error: expect { Net::HTTP.get(test_uri) }.to raise_error(WebMock::NetConnectNotAllowedError)
     
       expected WebMock::NetConnectNotAllowedError, got #<Errno::ECONNREFUSED: Failed to open TCP connection to other-local-hostname:9999 (Connection refused - connect(2) for "other-local-hostname" port 9999)> with backtrace:
         # /Users/david/.rvm/gems/ruby-2.7.2/gems/webmock-3.14.0/lib/webmock/http_lib_adapters/net_http.rb:148:in `start'
         # ./disable_net_connect_spec.rb:6:in `block (4 levels) in <top (required)>'
         # ./disable_net_connect_spec.rb:6:in `block (3 levels) in <top (required)>'
         # ./disable_net_connect_spec.rb:44:in `block (3 levels) in <top (required)>'
         # /Users/david/.rvm/gems/ruby-2.7.2/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
     Shared Example Group: "correctly" called from ./disable_net_connect_spec.rb:58
     # ./disable_net_connect_spec.rb:6:in `block (3 levels) in <top (required)>'
     # ./disable_net_connect_spec.rb:44:in `block (3 levels) in <top (required)>'
     # /Users/david/.rvm/gems/ruby-2.7.2/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  4) disable_net_connect! with net_http_connect_on_start with unreachable URI behaves like correctly can stub Net::HTTP requests
     Failure/Error: response = Net::HTTP.get_response(test_uri)
     
     Errno::ECONNREFUSED:
       Failed to open TCP connection to other-local-hostname:9999 (Connection refused - connect(2) for "other-local-hostname" port 9999)
     Shared Example Group: "correctly" called from ./disable_net_connect_spec.rb:58
     # /Users/david/.rvm/gems/ruby-2.7.2/gems/webmock-3.14.0/lib/webmock/http_lib_adapters/net_http.rb:148:in `start'
     # ./disable_net_connect_spec.rb:13:in `block (3 levels) in <top (required)>'
     # ./disable_net_connect_spec.rb:44:in `block (3 levels) in <top (required)>'
     # /Users/david/.rvm/gems/ruby-2.7.2/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Errno::ECONNREFUSED:
     #   Connection refused - connect(2) for "other-local-hostname" port 9999
     #   /Users/david/.rvm/gems/ruby-2.7.2/gems/webmock-3.14.0/lib/webmock/http_lib_adapters/net_http.rb:148:in `start'

Finished in 0.11899 seconds (files took 0.32782 seconds to load)
12 examples, 4 failures

Failed examples:

rspec ./disable_net_connect_spec.rb[1:2:2:1:1] # disable_net_connect! with net_http_connect_on_start with nonexistent URI behaves like correctly intercepts Net::HTTP connections
rspec ./disable_net_connect_spec.rb[1:2:2:1:2] # disable_net_connect! with net_http_connect_on_start with nonexistent URI behaves like correctly can stub Net::HTTP requests
rspec ./disable_net_connect_spec.rb[1:2:3:1:1] # disable_net_connect! with net_http_connect_on_start with unreachable URI behaves like correctly intercepts Net::HTTP connections
rspec ./disable_net_connect_spec.rb[1:2:3:1:2] # disable_net_connect! with net_http_connect_on_start with unreachable URI behaves like correctly can stub Net::HTTP requests
```

## System info

WebMock: 3.14.0
RSpec: 3.10.1
Ruby: 2.7.2p137
OS: macOS Catalina 10.15.7

**Comment by percyhanna** [comment]
We are running into the exact same issue. Using `net_http_connect_on_start: true` ends up causing the following problems:

1. Fails completely if the host is invalid
2. If the URI is `https`, then it will try to connect and potentially fail on invalid SSL certificate
3. Completely bypasses any existing stubbed requests

I'm not exactly sure what `net_http_connect_on_start` is meant to do, but it seems to be somewhat useless if it's actually having to open a connection to the server, etc.

**Comment by halo** [comment]
I noticed that [VCR doesn't replay](https://github.com/vcr/vcr/issues/482) external requests when my Wi-Fi is turned off. I can confirm that the solution introduced in webmock [3.18.1](https://rubygems.org/gems/webmock/versions/3.18.1) with [this pull request](https://github.com/bblimke/webmock/pull/975) solves the problem for me.

After upgrading webmock and changing my webmock settings to the following, I can run webmock offline again and it catches non-localhost traffic:

```ruby
net_http_connect_on_start: %w[127.0.0.1 localhost]
```
