### ISSUE TITLE
Memory issue in WebMock::Util::URI::NORMALIZED_URIS

### ISSUE THREAD

**Issue by mikecmpbll** [bblimke/webmock#997]
Hi folks

When tracing a memory problem with our test suite (memory grows steadily to >4GB over 2 hours), I noticed there were "leaked" string object allocations coming from `addressable/uri.rb`. When I dug a bit deeper they were being allocated with the following trace:

```
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/addressable-2.8.0/lib/addressable/uri.rb:2378:in `block in to_s'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/addressable-2.8.0/lib/addressable/uri.rb:2376:in `tap'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/addressable-2.8.0/lib/addressable/uri.rb:2376:in `to_s'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/addressable-2.8.0/lib/addressable/uri.rb:855:in `initialize'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/addressable-2.8.0/lib/addressable/uri.rb:2292:in `new'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/addressable-2.8.0/lib/addressable/uri.rb:2292:in `dup'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/webmock-3.8.3/lib/webmock/util/uri.rb:33:in `normalize_uri'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/webmock-3.8.3/lib/webmock/util/uri.rb:37:in `variations_of_uri_as_strings'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/webmock-3.8.3/lib/webmock/request_pattern.rb:143:in `matches?'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/webmock-3.8.3/lib/webmock/request_pattern.rb:37:in `matches?'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/webmock-3.8.3/lib/webmock/stub_registry.rb:58:in `block in request_stub_for'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/webmock-3.8.3/lib/webmock/stub_registry.rb:57:in `each'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/webmock-3.8.3/lib/webmock/stub_registry.rb:57:in `detect'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/webmock-3.8.3/lib/webmock/stub_registry.rb:57:in `request_stub_for'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/webmock-3.8.3/lib/webmock/stub_registry.rb:46:in `registered_request?'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/webmock-3.8.3/lib/webmock/webmock.rb:134:in `registered_request?'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/vcr-5.1.0/lib/vcr/library_hooks/webmock.rb:109:in `block in externally_stubbed?'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/vcr-5.1.0/lib/vcr/library_hooks/webmock.rb:21:in `with_global_hook_disabled'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/vcr-5.1.0/lib/vcr/library_hooks/webmock.rb:108:in `externally_stubbed?'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/vcr-5.1.0/lib/vcr/request_handler.rb:35:in `request_type'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/vcr-5.1.0/lib/vcr/request_handler.rb:10:in `handle'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/vcr-5.1.0/lib/vcr/library_hooks/webmock.rb:144:in `block in <module:WebMock>'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/webmock-3.8.3/lib/webmock/stub_registry.rb:28:in `block in register_global_stub'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/webmock-3.8.3/lib/webmock/request_pattern.rb:40:in `matches?'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/webmock-3.8.3/lib/webmock/stub_registry.rb:58:in `block in request_stub_for'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/webmock-3.8.3/lib/webmock/stub_registry.rb:57:in `each'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/webmock-3.8.3/lib/webmock/stub_registry.rb:57:in `detect'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/webmock-3.8.3/lib/webmock/stub_registry.rb:57:in `request_stub_for'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/webmock-3.8.3/lib/webmock/stub_registry.rb:50:in `response_for_request'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/webmock-3.8.3/lib/webmock/http_lib_adapters/net_http.rb:79:in `request'
/Users/mike.campbell/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/net/http.rb:1228:in `get'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/service_manager.rb:123:in `block in stop_server'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/service_manager.rb:96:in `block in connect_to_server'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/webmock-3.8.3/lib/webmock/http_lib_adapters/net_http.rb:123:in `start_without_connect'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/webmock-3.8.3/lib/webmock/http_lib_adapters/net_http.rb:150:in `start'
/Users/mike.campbell/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/net/http.rb:605:in `start'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/service_manager.rb:92:in `connect_to_server'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/service_manager.rb:121:in `stop_server'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/service_manager.rb:64:in `stop'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:183:in `quit'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/capybara-3.36.0/lib/capybara/selenium/driver.rb:293:in `quit'
/Users/mike.campbell/.rvm/gems/ruby-2.6.2/gems/capybara-3.36.0/lib/capybara/selenium/driver.rb:512:in `block in setup_exit_handler'
```

more digging through the trace; I found out that one such place these strings are sticking around is `WebMock::Util::URI::NORMALIZED_URIS`—everytime `WebMock::Util::URI::normalize_uri` is used with a unique URI, this data structure grows. after around 20 tests this object grows to >1000 size, and grows fairly linearly, so with our full test suite it gets huge. for context, this is a rails test suite, so web requests feature heavily (mostly to the embedded rails server).

i assume the aim is to cache the normalization, but is this anticipated behaviour? i suspect this will affect a lot of other people unless we're doing something weird/wrong that i'm unaware of. particularly with webdriver where i'm seeing lots of requests like this getting added to this structure:

```
http://127.0.0.1:9515/session/d8cac30dcfd1a7e5174a01efbb1d5073/execute/sync
http://127.0.0.1:9515/session/d8cac30dcfd1a7e5174a01efbb1d5073/elements
http://127.0.0.1:9515/session/d8cac30dcfd1a7e5174a01efbb1d5073/element/461f0f63-f4e2-4c7a-8561-25b35a5a3bf4/text
```

etc.

**Comment by mikecmpbll** [comment]
memory stuff in ruby is hard, man. turns out this isn't really as much of an issue as I thought, and certainly not to blame for my predicament.
